kind: pipeline
name: Drone

steps:
 - name: compile
   image: apon77/aosp:latest
   environment:
     token:
       from_secret: token
     chat_id:
       from_secret: chat_id
   commands:
      - sudo apt-get update &&sudo apt-get install tmate -y
      - sudo mkdir -p /usr/drone/bin/
      - sudo cp -fpr /usr/bin/tmate /usr/drone/bin/tmate
      - fail
